<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Company;
use App\Models\Job;

class CompaniesAndJobsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks temporarily
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Clear existing data to avoid duplicates
        Job::whereIn('company_id', [1, 2, 3, 4])->delete();
        Company::whereIn('id', [1, 2, 3, 4])->delete();
        User::whereIn('email', [
            'tech@innovations.com',
            'marketing@pro.com',
            'legal@experts.com',
            'admin@support.com'
        ])->delete();
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Create 4 companies with different specializations
        $companies = [
            [
                'id' => 1,
                'name' => 'شركة التقنيات المبتكرة',
                'email' => 'tech@innovations.com',
                'password' => Hash::make('password123'),
                'role' => 'company',
                'company_name' => 'شركة التقنيات المبتكرة',
                'description' => 'شركة رائدة في تطوير البرمجيات والحلول التقنية المتقدمة',
                'category' => 'برمجة وتطوير',
                'company_size' => '101-500',
                'website' => 'https://techinnovations.com',
                'location' => 'الرياض، السعودية',
                'phone' => '+966501234567',
                'logo' => 'https://picsum.photos/200/200?random=tech',
                'is_verified' => true,
                'founded_year' => 2018,
            ],
            [
                'id' => 2,
                'name' => 'وكالة التسويق الاحترافية',
                'email' => 'marketing@pro.com',
                'password' => Hash::make('password123'),
                'role' => 'company',
                'company_name' => 'وكالة التسويق الاحترافية',
                'description' => 'وكالة تسويق متخصصة في الحملات الرقمية وإدارة العلامات التجارية',
                'category' => 'تسويق وإعلان',
                'company_size' => '51-100',
                'website' => 'https://marketingpro.com',
                'location' => 'جدة، السعودية',
                'phone' => '+966512345678',
                'logo' => 'https://picsum.photos/200/200?random=marketing',
                'is_verified' => true,
                'founded_year' => 2020,
            ],
            [
                'id' => 3,
                'name' => 'مكتب الخبراء القانونيين',
                'email' => 'legal@experts.com',
                'password' => Hash::make('password123'),
                'role' => 'company',
                'company_name' => 'مكتب الخبراء القانونيين',
                'description' => 'مكتب قانوني متخصص في الاستشارات القانونية للشركات والأفراد',
                'category' => 'قانون واستشارات',
                'company_size' => '11-50',
                'website' => 'https://legalexperts.com',
                'location' => 'الدمام، السعودية',
                'phone' => '+966523456789',
                'logo' => 'https://picsum.photos/200/200?random=legal',
                'is_verified' => true,
                'founded_year' => 2015,
            ],
            [
                'id' => 4,
                'name' => 'مركز الإدارة والسكرتارية',
                'email' => 'admin@support.com',
                'password' => Hash::make('password123'),
                'role' => 'company',
                'company_name' => 'مركز الإدارة والسكرتارية',
                'description' => 'مركز متخصص في تقديم خدمات الإدارة والسكرتارية للشركات',
                'category' => 'إدارة وسكرتارية',
                'company_size' => '11-50',
                'website' => 'https://adminsupport.com',
                'location' => 'مكة المكرمة، السعودية',
                'phone' => '+966534567890',
                'logo' => 'https://picsum.photos/200/200?random=admin',
                'is_verified' => true,
                'founded_year' => 2019,
            ],
        ];

        // Create companies
        foreach ($companies as $companyData) {
            $user = User::create([
                'name' => $companyData['name'],
                'email' => $companyData['email'],
                'password' => $companyData['password'],
                'role' => $companyData['role'],
                'phone' => $companyData['phone'],
            ]);

            Company::create([
                'id' => $companyData['id'],
                'user_id' => $user->id,
                'company_name' => $companyData['company_name'],
                'description' => $companyData['description'],
                'category' => $companyData['category'],
                'company_size' => $companyData['company_size'],
                'website' => $companyData['website'],
                'location' => $companyData['location'],
                'phone' => $companyData['phone'],
                'logo' => $companyData['logo'],
                'is_verified' => $companyData['is_verified'],
                'founded_year' => $companyData['founded_year'],
            ]);
        }

        // Create 20 job posts covering various fields
        $jobs = [
            // Programming and Development Jobs (Company 1)
            [
                'company_id' => 1,
                'title' => 'مطور Full Stack أول',
                'description' => 'نبحث عن مطور Full Stack محترف للعمل على مشاريع الويب والموبايل',
                'requirements' => 'خبرة 3+ سنوات في React و Node.js، إتقان JavaScript و SQL',
                'location' => 'الرياض، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'onsite',
                'experience_level' => 'senior',
                'salary_min' => 8000,
                'salary_max' => 15000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 2,
            ],
            [
                'company_id' => 1,
                'title' => 'مطور تطبيقات موبايل',
                'description' => 'مطور تطبيقات موبايل لنظامي iOS و Android باستخدام React Native',
                'requirements' => 'خبرة 2+ سنوات في React Native، فهم قوي لمبادئ التصميم',
                'location' => 'الرياض، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'hybrid',
                'experience_level' => 'mid',
                'salary_min' => 7000,
                'salary_max' => 12000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 1,
            ],
            [
                'company_id' => 1,
                'title' => 'مطور واجهات أمامية (Frontend)',
                'description' => 'مطور Frontend متخصص في بناء واجهات مستخدم حديثة وتفاعلية',
                'requirements' => 'إتقان HTML5 و CSS3 و JavaScript، خبرة في React أو Vue.js',
                'location' => 'الرياض، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'remote',
                'experience_level' => 'entry',
                'salary_min' => 6000,
                'salary_max' => 10000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 3,
            ],
            [
                'company_id' => 1,
                'title' => 'مطور Backend',
                'description' => 'مطور Backend لبناء واجهات برمجية قوية وآمنة',
                'requirements' => 'خبرة في PHP/Laravel أو Node.js، فهم قواعد البيانات',
                'location' => 'الرياض، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'onsite',
                'experience_level' => 'mid',
                'salary_min' => 7000,
                'salary_max' => 12000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 2,
            ],
            [
                'company_id' => 1,
                'title' => 'مهندس DevOps',
                'description' => 'مهندس DevOps لإدارة البنية التحتية والعمليات التلقائية',
                'requirements' => 'خبرة في AWS/Docker، فهم CI/CD',
                'location' => 'الرياض، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'hybrid',
                'experience_level' => 'lead',
                'salary_min' => 9000,
                'salary_max' => 16000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 1,
            ],

            // Marketing Jobs (Company 2)
            [
                'company_id' => 2,
                'title' => 'مدير تسويق رقمي',
                'description' => 'مدير تسويق رقمي لإدارة الحملات الإعلانية الرقمية',
                'requirements' => 'خبرة 5+ سنوات في التسويق الرقمي، إتقان Google Ads و Facebook Ads',
                'location' => 'جدة، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'hybrid',
                'experience_level' => 'lead',
                'salary_min' => 8000,
                'salary_max' => 14000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 1,
            ],
            [
                'company_id' => 2,
                'title' => 'متخصص تسويق بالمحتوى',
                'description' => 'متخصص في إنشاء وإدارة المحتوى التسويقي',
                'requirements' => 'مهارات كتابة ممتازة، خبرة في إدارة وسائل التواصل الاجتماعي',
                'location' => 'جدة، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'remote',
                'experience_level' => 'mid',
                'salary_min' => 5000,
                'salary_max' => 8000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 2,
            ],
            [
                'company_id' => 2,
                'title' => 'مصمم جرافيك',
                'description' => 'مصمم جرافيك متخصص في التصميم التسويقي والعلامات التجارية',
                'requirements' => 'إتقان Adobe Creative Suite، خبرة في التصميم الرقمي',
                'location' => 'جدة، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'hybrid',
                'experience_level' => 'mid',
                'salary_min' => 4000,
                'salary_max' => 7000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 1,
            ],
            [
                'company_id' => 2,
                'title' => 'محلل تسويق',
                'description' => 'محلل تسويق لتحليل البيانات وإعداد التقارير',
                'requirements' => 'خبرة في تحليل البيانات، إتقان Excel و Google Analytics',
                'location' => 'جدة، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'onsite',
                'experience_level' => 'mid',
                'salary_min' => 6000,
                'salary_max' => 9000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 1,
            ],
            [
                'company_id' => 2,
                'title' => 'مدير وسائل التواصل الاجتماعي',
                'description' => 'مدير لإدارة حسابات وسائل التواصل الاجتماعي',
                'requirements' => 'خبرة في إدارة منصات التواصل، مهارات كتابة إبداعية',
                'location' => 'جدة، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'remote',
                'experience_level' => 'mid',
                'salary_min' => 5000,
                'salary_max' => 8000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 1,
            ],

            // Legal Jobs (Company 3)
            [
                'company_id' => 3,
                'title' => 'محامٍ شركات',
                'description' => 'محامٍ متخصص في قضايا الشركات والعقود',
                'requirements' => 'شهادة في القانون، خبرة 3+ سنوات في قضايا الشركات',
                'location' => 'الدمام، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'onsite',
                'experience_level' => 'senior',
                'salary_min' => 10000,
                'salary_max' => 18000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 2,
            ],
            [
                'company_id' => 3,
                'title' => 'مستشار قانوني',
                'description' => 'مستشار قانوني لتقديم الاستشارات القانونية للشركات',
                'requirements' => 'خبرة في الاستشارات القانونية، معرفة بالأنظمة السعودية',
                'location' => 'الدمام، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'hybrid',
                'experience_level' => 'senior',
                'salary_min' => 8000,
                'salary_max' => 14000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 1,
            ],
            [
                'company_id' => 3,
                'title' => 'مساعد قانوني',
                'description' => 'مساعد قانوني لدعم المحامين في إعداد المستندات والأبحاث',
                'requirements' => 'شهادة في القانون، مهارات بحث قوية',
                'location' => 'الدمام، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'onsite',
                'experience_level' => 'entry',
                'salary_min' => 4000,
                'salary_max' => 6000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 3,
            ],
            [
                'company_id' => 3,
                'title' => 'متخصص عقود',
                'description' => 'متخصص في صياغة ومراجعة العقود التجارية',
                'requirements' => 'خبرة في صياغة العقود، فهم قوي للقانون التجاري',
                'location' => 'الدمام، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'hybrid',
                'experience_level' => 'mid',
                'salary_min' => 6000,
                'salary_max' => 10000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 1,
            ],
            [
                'company_id' => 3,
                'title' => 'باحث قانوني',
                'description' => 'باحث قانوني لإجراء الأبحاث القانونية والتحليل',
                'requirements' => 'مهارات بحث ممتازة، إتقان اللغتين العربية والإنجليزية',
                'location' => 'الدمام، السعودية',
                'job_type' => 'part-time',
                'work_mode' => 'remote',
                'experience_level' => 'entry',
                'salary_min' => 3000,
                'salary_max' => 5000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 2,
            ],

            // Administrative and Secretarial Jobs (Company 4)
            [
                'company_id' => 4,
                'title' => 'مدير مكتب',
                'description' => 'مدير مكتب لإدارة العمليات اليومية وتنسيق الاجتماعات',
                'requirements' => 'خبرة 3+ سنوات في الإدارة، مهارات تنظيمية ممتازة',
                'location' => 'مكة المكرمة، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'onsite',
                'experience_level' => 'mid',
                'salary_min' => 6000,
                'salary_max' => 9000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 1,
            ],
            [
                'company_id' => 4,
                'title' => 'سكرتير تنفيذي',
                'description' => 'سكرتير تنفيذي لدعم الإدارة العليا',
                'requirements' => 'مهارات سكرتارية ممتازة، إتقان اللغتين العربية والإنجليزية',
                'location' => 'مكة المكرمة، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'onsite',
                'experience_level' => 'mid',
                'salary_min' => 4000,
                'salary_max' => 7000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 2,
            ],
            [
                'company_id' => 4,
                'title' => 'مساعد إداري',
                'description' => 'مساعد إداري لدعم العمليات الإدارية اليومية',
                'requirements' => 'مهارات تنظيمية، إتقان برامج المكتب',
                'location' => 'مكة المكرمة، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'hybrid',
                'experience_level' => 'entry',
                'salary_min' => 3000,
                'salary_max' => 5000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 3,
            ],
            [
                'company_id' => 4,
                'title' => 'منسق خدمات',
                'description' => 'منسق خدمات لتنسيق وتقديم خدمات العملاء',
                'requirements' => 'مهارات خدمة عملاء ممتازة، قدرة على التنسيق',
                'location' => 'مكة المكرمة، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'onsite',
                'experience_level' => 'entry',
                'salary_min' => 3500,
                'salary_max' => 5500,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 2,
            ],
            [
                'company_id' => 4,
                'title' => 'موظف استقبال',
                'description' => 'موظف استقبال لاستقبال الزوار وتوجيه المكالمات',
                'requirements' => 'مهارات تواصل ممتازة، مظهر لائق',
                'location' => 'مكة المكرمة، السعودية',
                'job_type' => 'full-time',
                'work_mode' => 'onsite',
                'experience_level' => 'entry',
                'salary_min' => 2500,
                'salary_max' => 4000,
                'salary_currency' => 'SAR',
                'salary_period' => 'month',
                'status' => 'published',
                'vacancies' => 2,
            ],
        ];

        // Create jobs
        foreach ($jobs as $jobData) {
            Job::create($jobData);
        }

        $this->command->info('✅ تم إنشاء 4 شركات و 20 وظيفة بنجاح!');
        $this->command->info('📊 تفاصيل الشركات:');
        $this->command->info('   1. شركة التقنيات المبتكرة (برمجة)');
        $this->command->info('   2. وكالة التسويق الاحترافية (تسويق)');
        $this->command->info('   3. مكتب الخبراء القانونيين (قانون)');
        $this->command->info('   4. مركز الإدارة والسكرتارية (إدارة)');
        $this->command->info('💼 الوظائف المنشورة: 20 وظيفة في مختلف المجالات');
    }
}
